// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportNutritionShop.Data;

#nullable disable

namespace SportNutritionShop.Migrations
{
    [DbContext(typeof(SportShopDbContext))]
    [Migration("20260519134518_InitialCreateWithSixProducts")]
    partial class InitialCreateWithSixProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SportNutritionShop.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Протеины"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Витамины"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Аксессуары"
                        });
                });

            modelBuilder.Entity("SportNutritionShop.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SportNutritionShop.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SportNutritionShop.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SportNutritionShop.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Сывороточный протеин премиум-качества для эффективного роста мышц.",
                            ImageUrl = "https://placehold.co/300x200/2563eb/ffffff?text=Whey",
                            Name = "Whey Gold Standard",
                            Price = 2499.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Изолят сывороточного белка с высокой степенью очистки, без сахара и лактозы.",
                            ImageUrl = "https://placehold.co/300x200/2563eb/ffffff?text=Isolate",
                            Name = "Whey Isolate Premium",
                            Price = 2890.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Рыбий жир высокой концентрации для поддержки сердца, сосудов и суставов.",
                            ImageUrl = "https://placehold.co/300x200/10b981/ffffff?text=Omega",
                            Name = "Omega-3 Premium",
                            Price = 890.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Усиленная формула Омега-3 с повышенным содержанием активных кислот EPA и DHA.",
                            ImageUrl = "https://placehold.co/300x200/10b981/ffffff?text=Omega+Ultra",
                            Name = "Omega-3 Ultra Concentrate",
                            Price = 1350.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Пластиковый шейкер с мерной сеткой для быстрого смешивания коктейлей.",
                            ImageUrl = "https://placehold.co/300x200/f59e0b/ffffff?text=Shaker",
                            Name = "Шейкер Pro 500ml",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Трехкомпонентный шейкер с дополнительными контейнерами под капсулы и порошок.",
                            ImageUrl = "https://placehold.co/300x200/f59e0b/ffffff?text=Smart+Shaker",
                            Name = "Smartshaker 3-в-1 600ml",
                            Price = 650.00m
                        });
                });

            modelBuilder.Entity("SportNutritionShop.Data.Entities.Order", b =>
                {
                    b.HasOne("SportNutritionShop.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SportNutritionShop.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("SportNutritionShop.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportNutritionShop.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SportNutritionShop.Data.Entities.Product", b =>
                {
                    b.HasOne("SportNutritionShop.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SportNutritionShop.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SportNutritionShop.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
